// AUTO-GENERATED by scripts/generate-tool-risk.ts - do not hand-edit.
// Regenerate with `npx tsx scripts/generate-tool-risk.ts` after `npm run toolgen`
// picks up new/changed tools from the Firefly III OpenAPI spec, then review any
// entries whose comment says UNCLASSIFIED-fallback or *-fallback before trusting them.
import type { ToolRiskEntry } from './tool-risk-types.js';

export const TOOL_RISK_MAP: Record<string, ToolRiskEntry> = {
  // name-override
  bulk_update_transactions: { risk: 'administrative', requiredPreset: 'administrative', movesMoney: true, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // split:currencies:write
  default_currency: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // split:accounts:delete
  delete_account: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:attachments
  delete_attachment: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:bills
  delete_bill: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // split:budgets:delete
  delete_budget: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // split:budgets:delete
  delete_budget_limit: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // split:categories:delete
  delete_category: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // split:currencies:delete
  delete_currency: { risk: 'destructive', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:links
  delete_link_type: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:object_groups
  delete_object_group: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:piggy_banks
  delete_piggy_bank: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:recurrences
  delete_recurrence: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:rules
  delete_rule: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:rule_groups
  delete_rule_group: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:currency_exchange_rates
  delete_specific_currency_exchange_rate: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:currency_exchange_rates
  delete_specific_currency_exchange_rates: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // split:tags:delete
  delete_tag: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // split:transactions:delete
  delete_transaction: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: true, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // name-override
  delete_transaction_journal: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: true, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:links
  delete_transaction_link: { risk: 'destructive', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: false, requiresConfirmation: true },
  // name-override
  delete_user: { risk: 'administrative', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  delete_webhook: { risk: 'destructive', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  delete_webhook_message: { risk: 'destructive', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  delete_webhook_message_attempt: { risk: 'destructive', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: true, requiresConfirmation: true },
  // name-override
  destroy_data: { risk: 'administrative', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: true, requiresConfirmation: true },
  // split:currencies:write
  disable_currency: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:attachments
  download_attachment: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:write
  enable_currency: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // name-override:export
  export_accounts: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_bills: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_budgets: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_categories: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_piggies: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_recurring: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_rules: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_tags: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override:export
  export_transactions: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: false },
  // name-override
  fire_rule: { risk: 'write', requiredPreset: 'advanced', movesMoney: true, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // name-override
  fire_rule_group: { risk: 'write', requiredPreset: 'advanced', movesMoney: true, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:about
  get_about: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:accounts:read
  get_account: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->accounts
  get_accounts_ac: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:attachments
  get_attachment: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:available_budgets:read
  get_available_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:summary
  get_basic_summary: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:bills
  get_bill: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->bills
  get_bills_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  get_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  get_budget_limit: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->budgets
  get_budgets_ac: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->categories
  get_categories_ac: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:categories:read
  get_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:charts
  get_chart_account_overview: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:configuration
  get_configuration: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // name-override
  get_cron: { risk: 'administrative', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // autocomplete->currencies
  get_currencies_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->currencies_code
  get_currencies_code_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  get_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:about
  get_current_user: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  get_link_type: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  get_native_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:object_groups
  get_object_group: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->object_groups
  get_object_groups_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->piggies
  get_piggies_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->piggies_balance
  get_piggies_balance_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:piggy_banks
  get_piggy_bank: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:preferences
  get_preference: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:recurrences
  get_recurrence: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->recurring
  get_recurring_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rules
  get_rule: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rule_groups
  get_rule_group: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->rule_groups
  get_rule_groups_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->rules
  get_rules_ac: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:configuration
  get_single_configuration: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:webhooks
  get_single_webhook_message: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  get_single_webhook_message_attempt: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // split:tags:read
  get_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->tag
  get_tag_ac: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:read
  get_transaction: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:read
  get_transaction_by_journal: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  get_transaction_link: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->transaction_types
  get_transaction_types_ac: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->transactions
  get_transactions_ac: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // autocomplete->transactions
  get_transactions_idac: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:users
  get_user: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:user_groups
  get_user_group: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  get_webhook: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  get_webhook_message_attempts: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  get_webhook_messages: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:insight
  insight_expense_asset: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_bill: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_expense: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_no_bill: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_no_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_no_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_no_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_expense_total: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_income_asset: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_income_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_income_no_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_income_no_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_income_revenue: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_income_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_income_total: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_transfer_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_transfer_no_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_transfer_no_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_transfer_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_transfer_total: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:insight
  insight_transfers: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:accounts:read
  list_account: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_account_by_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:attachments
  list_attachment: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:accounts:read
  list_attachment_by_account: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:bills
  list_attachment_by_bill: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  list_attachment_by_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:categories:read
  list_attachment_by_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:piggy_banks
  list_attachment_by_piggy_bank: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:tags:read
  list_attachment_by_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:read
  list_attachment_by_transaction: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:available_budgets:read
  list_available_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_available_budget_by_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:bills
  list_bill: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_bill_by_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:object_groups
  list_bill_by_object_group: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  list_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  list_budget_limit: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  list_budget_limit_by_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_budget_limit_by_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:categories:read
  list_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:currency_exchange_rates
  list_currency_exchange_rates: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:piggy_banks
  list_event_by_piggy_bank: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:read
  list_event_by_transaction: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  list_link_type: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:read
  list_links_by_journal: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:object_groups
  list_object_groups: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:piggy_banks
  list_piggy_bank: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:accounts:read
  list_piggy_bank_by_account: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:object_groups
  list_piggy_bank_by_object_group: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:preferences
  list_preference: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:recurrences
  list_recurrence: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_recurrence_by_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rules
  list_rule: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:bills
  list_rule_by_bill: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_rule_by_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rule_groups
  list_rule_by_group: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rule_groups
  list_rule_group: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:currency_exchange_rates
  list_specific_currency_exchange_rate: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:currency_exchange_rates
  list_specific_currency_exchange_rates: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:tags:read
  list_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:read
  list_transaction: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:accounts:read
  list_transaction_by_account: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:bills
  list_transaction_by_bill: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  list_transaction_by_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  list_transaction_by_budget_limit: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:categories:read
  list_transaction_by_category: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:read
  list_transaction_by_currency: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  list_transaction_by_link_type: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:recurrences
  list_transaction_by_recurrence: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:tags:read
  list_transaction_by_tag: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  list_transaction_link: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:read
  list_transaction_without_budget: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:users
  list_user: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:user_groups
  list_user_groups: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  list_webhook: { risk: 'read', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // name-override
  purge_data: { risk: 'administrative', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: true, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:search
  search_accounts: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:search
  search_transactions: { risk: 'read', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // name-override
  set_configuration: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // split:accounts:write
  store_account: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:attachments
  store_attachment: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:bills
  store_bill: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:write
  store_budget: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:write
  store_budget_limit: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:categories:create-safe
  store_category: { risk: 'write', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:write
  store_currency: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:currency_exchange_rates
  store_currency_exchange_rate: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  store_link_type: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:piggy_banks
  store_piggy_bank: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:preferences
  store_preference: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:recurrences
  store_recurrence: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rules
  store_rule: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rule_groups
  store_rule_group: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:tags:create-safe
  store_tag: { risk: 'write', requiredPreset: 'safe', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:write
  store_transaction: { risk: 'write', requiredPreset: 'safe', movesMoney: true, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  store_transaction_link: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:users
  store_user: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  store_webhook: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // name-override
  submit_webook: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:rules
  test_rule: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rule_groups
  test_rule_group: { risk: 'read', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // name-override
  trigger_transaction_webhook: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // split:accounts:write
  update_account: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:attachments
  update_attachment: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:bills
  update_bill: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:write
  update_budget: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:budgets:write
  update_budget_limit: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:categories:update-advanced
  update_category: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:currencies:write
  update_currency: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: true },
  // tag:links
  update_currency_exchange_rate: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  update_link_type: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:object_groups
  update_object_group: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:piggy_banks
  update_piggy_bank: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:preferences
  update_preference: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:recurrences
  update_recurrence: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rules
  update_rule: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:rule_groups
  update_rule_group: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:tags:update-advanced
  update_tag: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // split:transactions:write
  update_transaction: { risk: 'write', requiredPreset: 'safe', movesMoney: true, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:links
  update_transaction_link: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
  // tag:users
  update_user: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:user_groups
  update_user_group: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // tag:webhooks
  update_webhook: { risk: 'write', requiredPreset: 'administrative', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: true, requiresConfirmation: true },
  // name-override
  upload_attachment: { risk: 'write', requiredPreset: 'advanced', movesMoney: false, permanentlyDeletesData: false, affectsOtherUsers: false, requiresConfirmation: false },
};
